# Generated by Django 2.1.7 on 2019-02-22 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20190222_1300'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='budget_left',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
